# Generated by Django 3.0.8 on 2020-11-27 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authe', '0002_auto_20201127_1510'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('age', models.ImageField(upload_to='')),
            ],
        ),
    ]
