# Generated by Django 3.0.8 on 2020-11-27 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authe', '0003_person'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Person',
        ),
    ]
