# Generated by Django 3.0.8 on 2020-11-27 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authe', '0004_delete_person'),
    ]

    operations = [
        migrations.CreateModel(
            name='Магазины',
            fields=[
                ('номер', models.IntegerField(primary_key=True, serialize=False)),
                ('класс', models.CharField(max_length=50)),
                ('заведующий', models.CharField(max_length=100)),
                ('название', models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='ОтделМагазин',
            fields=[
                ('номеротдела', models.IntegerField(primary_key=True, serialize=False)),
                ('тип', models.CharField(max_length=70)),
                ('заведующий', models.CharField(max_length=70)),
                ('номермагазина', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authe.Магазины')),
            ],
        ),
        migrations.CreateModel(
            name='ТоварМагазинов',
            fields=[
                ('артикул', models.AutoField(primary_key=True, serialize=False)),
                ('название', models.CharField(max_length=100)),
                ('тип', models.CharField(max_length=100)),
                ('количество', models.IntegerField()),
                ('цена', models.IntegerField()),
                ('номеротдела', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='authe.ОтделМагазин')),
            ],
        ),
    ]
