# Generated by Django 3.0.8 on 2020-11-27 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authe', '0006_auto_20201127_1638'),
    ]

    operations = [
        migrations.AddField(
            model_name='товармагазинов',
            name='номермагазина',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='authe.Магазины'),
            preserve_default=False,
        ),
    ]
