# Generated by Django 3.0.8 on 2020-12-02 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authe', '0008_auto_20201129_1231'),
    ]

    operations = [
        migrations.CreateModel(
            name='ТорговыеБазы',
            fields=[
                ('номер', models.AutoField(primary_key=True, serialize=False)),
                ('название', models.CharField(max_length=100)),
                ('заведующий', models.CharField(max_length=100)),
                ('город', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ТоварБазы',
            fields=[
                ('артикул', models.AutoField(primary_key=True, serialize=False)),
                ('тип', models.CharField(max_length=70)),
                ('количество', models.IntegerField()),
                ('цена', models.IntegerField()),
                ('база', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authe.ТорговыеБазы')),
            ],
        ),
        migrations.AddField(
            model_name='магазины',
            name='торговаябаза',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='authe.ТорговыеБазы'),
        ),
    ]
