# Generated by Django 3.0.8 on 2020-12-02 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authe', '0009_auto_20201202_1753'),
    ]

    operations = [
        migrations.AddField(
            model_name='товарбазы',
            name='название',
            field=models.CharField(max_length=70, null=True),
        ),
    ]
