# Generated by Django 3.0.8 on 2020-12-02 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authe', '0010_товарбазы_название'),
    ]

    operations = [
        migrations.CreateModel(
            name='ТипТоваровМагазин',
            fields=[
                ('номер', models.AutoField(primary_key=True, serialize=False)),
                ('тип', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='товармагазинов',
            name='тип',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='authe.ТипТоваровМагазин'),
        ),
    ]
